# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\victo\Desktop\PUC\Modular\Projeto\Ludo-Python\Interface\FimdeJogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FimdeJogo(object):
    def setupUi(self, FimdeJogo):
        FimdeJogo.setObjectName("FimdeJogo")
        FimdeJogo.resize(606, 294)
        FimdeJogo.setMinimumSize(QtCore.QSize(606, 294))
        FimdeJogo.setMaximumSize(QtCore.QSize(606, 294))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagens/ludo_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FimdeJogo.setWindowIcon(icon)
        FimdeJogo.setStyleSheet("QWidget#FimdeJogo {\n"
"    background-color: rgb(247, 255, 93);\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 4px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0,0,0);\n"
"    border-radius: 4;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(FimdeJogo)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.labelTitle = QtWidgets.QLabel(FimdeJogo)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle, 0, QtCore.Qt.AlignTop)
        self.winnerWidget = QtWidgets.QWidget(FimdeJogo)
        self.winnerWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.winnerWidget.setObjectName("winnerWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.winnerWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.winnerImage = QtWidgets.QLabel(self.winnerWidget)
        self.winnerImage.setMaximumSize(QtCore.QSize(150, 16777215))
        self.winnerImage.setText("")
        self.winnerImage.setAlignment(QtCore.Qt.AlignCenter)
        self.winnerImage.setObjectName("winnerImage")
        self.horizontalLayout.addWidget(self.winnerImage)
        self.winnerName = QtWidgets.QLabel(self.winnerWidget)
        self.winnerName.setMinimumSize(QtCore.QSize(430, 128))
        self.winnerName.setMaximumSize(QtCore.QSize(430, 128))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.winnerName.setFont(font)
        self.winnerName.setText("")
        self.winnerName.setAlignment(QtCore.Qt.AlignCenter)
        self.winnerName.setObjectName("winnerName")
        self.horizontalLayout.addWidget(self.winnerName)
        self.verticalLayout.addWidget(self.winnerWidget)
        self.ConfirmCancelButtons = QtWidgets.QWidget(FimdeJogo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfirmCancelButtons.sizePolicy().hasHeightForWidth())
        self.ConfirmCancelButtons.setSizePolicy(sizePolicy)
        self.ConfirmCancelButtons.setStyleSheet("")
        self.ConfirmCancelButtons.setObjectName("ConfirmCancelButtons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ConfirmCancelButtons)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonExit = QtWidgets.QPushButton(self.ConfirmCancelButtons)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 37, 40);")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout_3.addWidget(self.pushButtonExit)
        self.pushButtonMenu = QtWidgets.QPushButton(self.ConfirmCancelButtons)
        self.pushButtonMenu.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMenu.setFont(font)
        self.pushButtonMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMenu.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.pushButtonMenu.setObjectName("pushButtonMenu")
        self.horizontalLayout_3.addWidget(self.pushButtonMenu)
        self.verticalLayout.addWidget(self.ConfirmCancelButtons)

        self.retranslateUi(FimdeJogo)
        QtCore.QMetaObject.connectSlotsByName(FimdeJogo)

    def retranslateUi(self, FimdeJogo):
        _translate = QtCore.QCoreApplication.translate
        FimdeJogo.setWindowTitle(_translate("FimdeJogo", "Fim de Jogo"))
        self.labelTitle.setText(_translate("FimdeJogo", "Fim de Jogo"))
        self.pushButtonExit.setText(_translate("FimdeJogo", "Sair do Jogo"))
        self.pushButtonMenu.setText(_translate("FimdeJogo", "Voltar ao Menu"))
import Interface.Resources.resources_rc
