# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\victo\Desktop\PUC\Modular\Projeto\Ludo-Python\Interface\Historico_Modulo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Historico_Modulo(object):
    def setupUi(self, Historico_Modulo):
        Historico_Modulo.setObjectName("Historico_Modulo")
        Historico_Modulo.resize(728, 83)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Historico_Modulo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matchNumber = QtWidgets.QLabel(Historico_Modulo)
        self.matchNumber.setMinimumSize(QtCore.QSize(140, 0))
        self.matchNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        self.matchNumber.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.matchNumber.setFont(font)
        self.matchNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.matchNumber.setObjectName("matchNumber")
        self.horizontalLayout.addWidget(self.matchNumber, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.winnerImage = QtWidgets.QLabel(Historico_Modulo)
        self.winnerImage.setMinimumSize(QtCore.QSize(70, 0))
        self.winnerImage.setMaximumSize(QtCore.QSize(70, 16777215))
        self.winnerImage.setStyleSheet("image: url(:/Imagens/playerBlue.png);")
        self.winnerImage.setText("")
        self.winnerImage.setObjectName("winnerImage")
        self.horizontalLayout.addWidget(self.winnerImage)
        self.winnerName = QtWidgets.QLabel(Historico_Modulo)
        self.winnerName.setMinimumSize(QtCore.QSize(120, 0))
        self.winnerName.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.winnerName.setFont(font)
        self.winnerName.setObjectName("winnerName")
        self.horizontalLayout.addWidget(self.winnerName, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.numberPlayers = QtWidgets.QLabel(Historico_Modulo)
        self.numberPlayers.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.numberPlayers.setFont(font)
        self.numberPlayers.setAlignment(QtCore.Qt.AlignCenter)
        self.numberPlayers.setObjectName("numberPlayers")
        self.horizontalLayout.addWidget(self.numberPlayers, 0, QtCore.Qt.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.infoButton = QtWidgets.QPushButton(Historico_Modulo)
        self.infoButton.setMinimumSize(QtCore.QSize(60, 60))
        self.infoButton.setMaximumSize(QtCore.QSize(60, 60))
        self.infoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.infoButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.infoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Imagens/infoIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon)
        self.infoButton.setIconSize(QtCore.QSize(48, 48))
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(Historico_Modulo)
        QtCore.QMetaObject.connectSlotsByName(Historico_Modulo)

    def retranslateUi(self, Historico_Modulo):
        _translate = QtCore.QCoreApplication.translate
        Historico_Modulo.setWindowTitle(_translate("Historico_Modulo", "Form"))
        self.matchNumber.setText(_translate("Historico_Modulo", "P1"))
        self.winnerName.setText(_translate("Historico_Modulo", "Jogadorxxx"))
        self.numberPlayers.setText(_translate("Historico_Modulo", "X Jogadores"))
import Interface.Resources.resources_rc
